name: auto-merge

on:
  pull_request:

jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.GH_APPS_ID }}
          private_key: ${{ secrets.GH_APPS_PRIVATE_KEY }}
        continue-on-error: true
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ steps.generate-token.outputs.token }}
