name: Build Containers

on: [pull_request]

env:
  SPARQL_ENDPOINT_URL: https://prismdb.takanakahiko.me/sparql
  DBA_PASSWORD: hogehuga

jobs:

  delivery:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        SERVICE_NAME: [web, virtuoso]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build web
        if: matrix.SERVICE_NAME == 'web'
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: ./web
          build-args: |
            SPARQL_ENDPOINT_URL=${{ env.SPARQL_ENDPOINT_URL }}

      - name: Build virtuoso
        if: matrix.SERVICE_NAME == 'virtuoso'
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: ./virtuoso
          build-contexts: |
            csv2rdf=./csv2rdf
            data=./_data
          build-args: |
            DBA_PASSWORD=${{ env.DBA_PASSWORD }}
