name: Build Containers

on: [pull_request]

env:
  SPARQL_ENDPOINT_URL: https://prismdb.takanakahiko.me/sparql
  DBA_PASSWORD: hogehuga

jobs:

  delivery:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        SERVICE_NAME: [web, virtuoso]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build web
        if: matrix.SERVICE_NAME == 'web'
        uses: docker/build-push-action@v6
        with:
          context: ./web
          build-args: |
            SPARQL_ENDPOINT_URL=${{ env.SPARQL_ENDPOINT_URL }}

      - name: Build virtuoso
        if: matrix.SERVICE_NAME == 'virtuoso'
        uses: docker/build-push-action@v6
        with:
          context: ./virtuoso
          build-contexts: |
            csv2rdf=./csv2rdf
            data=./_data
          build-args: |
            DBA_PASSWORD=${{ env.DBA_PASSWORD }}
