name: Delivery Containers

on: 
  push:
    branches:
      - master

env:
  GCP_PROJECT: prismdb
  GCP_REGION: asia-northeast1

jobs:

  delivery:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        SERVICE_NAME: [web, virtuoso]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: prepara rdfs
        working-directory: csv2rdf
        run: | 
          npm ci
          BASE_URL=https://prismdb.takanakahiko.me npm start

      - name: GCP Authenticate
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '283.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - if: matrix.SERVICE_NAME == 'web'
        run: echo ::set-env name=BUILD_ARGS::'--build-arg SPARQL_ENDPOINT_URL=${{ secrets.SPARQL_ENDPOINT_URL }}'
      
      - if: matrix.SERVICE_NAME == 'virtuoso'
        run: echo ::set-env name=BUILD_ARGS::'--build-arg DBA_PASSWORD=${{ secrets.DBA_PASSWORD }}'

      - name: Set the docker image name
        run: echo ::set-env name=IMAGE::'asia.gcr.io/${{env.GCP_PROJECT}}/${{ matrix.SERVICE_NAME }}:${{ github.sha }}'

      - name: Build a docker image
        run: docker build ${{ matrix.SERVICE_NAME }} -t $IMAGE $BUILD_ARGS

      - name: Push the docker image
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy ${{ matrix.SERVICE_NAME }} \
              --image $IMAGE \
              --project $GCP_PROJECT \
              --region $GCP_REGION \
              --platform managed \
              --memory 512Mi \
              --allow-unauthenticated \
              --quiet \
              $DEPLOY_ARGS
