name: rdflint

on: [pull_request]

jobs:
  rdflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: imas/setup-rdflint@v1
      - working-directory: csv2rdf
        run: | 
          npm ci
          BASE_URL=https://prismdb.takanakahiko.me npm start
      - run: rdflint -config virtuoso/rdflint-config.yml -targetdir virtuoso/data/toLoad
