name: re-generate

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  re-generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - working-directory: csv2rdf
      name: update shops
      run: |
        npm ci
        $(npm bin)/ts-node tools/update-shops-primagi.ts
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.GH_APPS_ID }}
        private_key: ${{ secrets.GH_APPS_PRIVATE_KEY }}
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.generate-token.outputs.token }}
        committer: GitHub <noreply@github.com>
        title: 'お店情報のアップデート'
        body: |
          お店情報の自動アップデートです！ #274
        labels: |
          automerge
    - name: Slack Notification
      uses: lazy-actions/slatify@master
      if: "! success()" # cronで実行されるので失敗時のみ通知する
      continue-on-error: true
      with:
        job_name: '*re-generate*'
        type: ${{ job.status }}
        url: ${{ secrets.SLACK_WEBHOOK }}
        token: ${{ secrets.GITHUB_TOKEN }}
